### PR TITLE
Fix nonce by changing it from a random byte array...

### LINKED ISSUE #14: GCM cannot be used with random nonces
A nonce collision with GCM is devastating, and there is a 2^{-43} probability of such a collision every single time a message is generated.

### PR DESCRIPTION
**Pull request by njaremko**
Fix nonce by changing it from a random byte array to an incrementing counter that is converted into a byte array.

Resolves #14

### CODE REVIEW

**Comment by leonklingele** [comment]
_Please_ don't merge. There needs to be a big `NOTE` / `WARNING` that one should _not_ simply start the counter at 0. The counter value has to be stored somehow, so that even if your app crashes and you continue encrypting with the same key, the nonce will not repeat.
Random nonces >> This solution

**Comment by twitchyliquid64** [comment]
Random nonces have a 2^-43 chance of badness. The chance of a user of this library fucking it up because they have to initialize the nonce, store it, make sure it does not repeat etc is much, much greater,

**Comment by leonklingele** [comment]
Quoting [NIST Special Publication 800-38D](http://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf), 8.3 "Constraints on the Number of Invocations":

> The total number of invocations of the authenticated encryption function shall not exceed 2^32, including all IV lengths and all instances of the authenticated encryption function with the given key.

I don't really trust them, but this seems absolutely reasonable.

**Comment by twitchyliquid64** [comment]
Would it be worth adding to the docs / comments in encrypt.go that they shouldnt use invoke ad infinitum (ie 2^32)? Or too much of an edge case?

**Comment by gtank** [comment]
The real solution to this problem is to use a different AEAD construction when a comparably optimized one becomes widely available. For now, I think this is too much of an edge case to warrant making the encryption functions stateful.

That said, FUTURE PEOPLE if you're encrypting billions of messages with this library please get in touch so we can come up with something better.

**Comment by leonklingele** [comment]
Well, XSalsa20 (supporting 192 bit nonces) is available in the official crypto package: https://github.com/golang/crypto/blob/master/salsa20/salsa20.go

**Comment by njaremko** [comment]
This issue is closed, any future conversation should be in another issue. Also, this pull request hasn't been merged for 8 months, not sure why everyone's freaking out about possibly merging it...

**Pull request closed without merging**
